# Generated by Django 3.0.2 on 2020-01-06 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=60)),
                ('bank_card_id', models.BigIntegerField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('discount_type', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('pr_type', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('disc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Discount')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'db_table': 'product_discount',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='disc',
            field=models.ManyToManyField(through='store.ProductDiscount', to='store.Discount'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_total', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Client')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Product')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
